### PR TITLE
Fixed segv in latest ruby-head when bad utf-8 give into Stringprep.nfkc_normalize

### PR DESCRIPTION
**Pull request by ukolovda**
Addressed to #9

### CODE REVIEW

**Review by deepfryed — APPROVED** [review]
Thanks Dmitry, much appreciated!

**Comment by deepfryed** [comment]
Published v0.1.3

**Comment by ukolovda** [comment]
> Published v0.1.3

Oh, with 0.1.3 the Addressable gem tests become failed with invalid parameters... 
I.e.:
```
Addressable::URI when parsed from 'http://example.com/%E8' should not raise an exception when normalized
     Failure/Error:
       expect do
         @uri.normalize
       end.not_to raise_error

       expected no Exception, got #<NoMethodError: undefined method `force_encoding' for nil:NilClass> with backtrace:
         # ./lib/addressable/uri.rb:590:in `normalize_component'
         # ./lib/addressable/uri.rb:1559:in `block in normalized_path'
         # ./lib/addressable/uri.rb:1558:in `map'
         # ./lib/addressable/uri.rb:1558:in `normalized_path'
         # ./lib/addressable/uri.rb:2198:in `normalize'
```

https://github.com/ukolovda/addressable/runs/4064749021?check_suite_focus=true

**Comment by deepfryed** [comment]
```
if (buf == NULL) {
    return Qnil;
  }
```

@ukolovda that makes sense, preserves the result type. I think addressable should handle nil return value, raising an error in ruby-idn is not going to be helpful unless we intend to rescue that in the callers.

**Comment by dentarg** [comment]
Hmm... @deepfryed isn't there a suitable error that could be raised? See the list on https://josefsson.org/idn.php/ (disclaimer: haven't at all looked into what's going on here (yet))

**Comment by ukolovda** [comment]
> ```
> if (buf == NULL) {
>     return Qnil;
>   }
> ```
> 
> @ukolovda that makes sense, preserves the result type. I think addressable should handle nil return value, raising an error in ruby-idn is not going to be helpful unless we intend to rescue that in the callers.

Ruby before 3.1 raises `ArgumentError: NULL pointer given` for rb_utf8_str_new_cstr(NULL). But current development trunk crushing with Segmentation Fault.

**Comment by dentarg** [comment]
> Ruby before 3.1 raises `ArgumentError: NULL pointer given` for rb_utf8_str_new_cstr(NULL). But current development trunk crushing with Segmentation Fault.

Looks like a bug with Ruby: https://bugs.ruby-lang.org/issues/18280#note-1

**Comment by deepfryed** [comment]
@ukolovda  We can raise an EncodingError which is more appropriate. Would that allow the addressable tests to pass ?

**Comment by dentarg** [comment]
> @ukolovda We can raise an EncodingError which is more appropriate. Would that allow the addressable tests to pass ?

No, but `ArgumentError` would, see https://github.com/sporkmonger/addressable/pull/441#issuecomment-956774728

Addressable could of course be changed to rescue `EncodingError` too, but everyone would have to update to that newer version (and I'm not sure if/when a new Addressable release would be made, current maintainer is less and less active). 

I suspect Addressable rescue `ArgumentError` because the pure IDNA version in Addressable throws `ArgumentError`.

**Comment by deepfryed** [comment]
@dentarg @ukolovda patched in main branch, please take a look and let me know if that works.

https://github.com/deepfryed/idn-ruby/commit/3b4374f613f4301b3288a9727ee9e620145e2f15

**Comment by dentarg** [comment]
@deepfryed It [works](https://github.com/dentarg/addressable/actions/runs/1410117581), thanks!

**Comment by deepfryed** [comment]
yanked v0.1.3 and published v0.1.4, thanks

**Comment by ukolovda** [comment]
Thank you, @deepfryed , @dentarg !
I'm sorry for incompacible patch, I should be check it more accuracy.

**Comment by deepfryed** [comment]
@ukolovda no problem, thanks for following up.

**Pull request merged**
